import type {
  AnalysisResponse,
  ChartPayload,
  PredictionsResponse,
  RankingsResponse,
  SymbolSearchResult,
  UIView,
  UIFundamental,
  UITechnical,
} from "@/lib/types";

export const mockTechnical: UITechnical = {
  trend: "Bullish",
  rsi: 55.3,
  macd_signal: "bullish",
  moving_averages: {
    sma_20: 178.5,
    sma_50: 172.3,
    sma_200: 165.1,
    ema_12: 179.2,
    ema_26: 175.8,
  },
  support_resistance: {
    support: 170.0,
    resistance: 190.0,
    support_2: 160.0,
    resistance_2: 200.0,
    pivot_point: 180.0,
  },
  raw_payload: null,
};

export const mockFundamental: UIFundamental = {
  models: [
    {
      name: "DCF",
      fair_value: 195.0,
      weight: 0.4,
      confidence: "high",
      details: {},
    },
    {
      name: "P/E Relative",
      fair_value: 188.0,
      weight: 0.3,
      confidence: "medium",
      details: {},
    },
    {
      name: "GGM",
      fair_value: 201.0,
      weight: 0.3,
      confidence: "low",
      details: {},
    },
  ],
  forward_guidance: {
    revenue_growth_pct: 8.5,
    eps_estimate: 6.75,
    guidance_period: "FY2025",
    source: "Company guidance",
    revenue_low: 53_500_000_000,
    revenue_high: 56_500_000_000,
    revenue_mid: 55_000_000_000,
    filing_date: "2025-01-28",
  },
  notes: ["Strong free cash flow generation", "Share buyback program active"],
  raw_payload: null,
};

export const mockView: UIView = {
  symbol: "AAPL",
  company_name: "Apple Inc.",
  sector: "Technology",
  industry: "Consumer Electronics",
  timestamp: "2025-01-15T10:30:00Z",
  summary: {
    action: "Buy",
    composite_score: 72,
    price: 182.5,
    fair_value: 195.0,
    target_return_pct: 6.8,
    valuation_basis: "DCF",
    data_quality: "High",
    thesis: "Strong fundamentals with growing services revenue.",
    key_risks: ["Regulatory pressure", "Supply chain constraints"],
    key_catalysts: ["AI integration", "Services growth"],
  },
  fundamental: mockFundamental,
  technical: mockTechnical,
  signals: [
    { label: "RSI", value: "55.3", sentiment: "neutral" },
    { label: "MACD", value: "Bullish", sentiment: "good" },
    { label: "Trend", value: "Bullish", sentiment: "good" },
  ],
};

export const mockAnalysisResponse: AnalysisResponse = {
  symbol: "AAPL",
  status: "success",
  cached: false,
  timestamp: "2025-01-15T10:30:00Z",
  data: mockView,
};

export const mockChartPayload: ChartPayload = {
  symbol: "AAPL",
  days: 180,
  candles: [
    { date: "2025-01-13", open: 180.0, high: 183.0, low: 179.0, close: 182.0 },
    { date: "2025-01-14", open: 182.0, high: 185.0, low: 181.0, close: 184.0 },
    { date: "2025-01-15", open: 184.0, high: 186.0, low: 182.5, close: 182.5 },
  ],
  volume: [
    { date: "2025-01-13", volume: 50_000_000, obv: 50_000_000 },
    { date: "2025-01-14", volume: 45_000_000, obv: 95_000_000 },
    { date: "2025-01-15", volume: 55_000_000, obv: 40_000_000 },
  ],
  indicators: {
    macd: [
      { date: "2025-01-13", macd: 1.2, signal: 0.8, histogram: 0.4 },
      { date: "2025-01-14", macd: 1.5, signal: 1.0, histogram: 0.5 },
      { date: "2025-01-15", macd: 1.3, signal: 1.1, histogram: 0.2 },
    ],
    rsi: [
      { date: "2025-01-13", rsi: 55.0 },
      { date: "2025-01-14", rsi: 58.0 },
      { date: "2025-01-15", rsi: 55.3 },
    ],
  },
  overlays: [
    { date: "2025-01-13", sma_20: 178.5, sma_50: 172.3, sma_200: 165.1, ema_20: 179.0, ema_50: 173.0, bb_upper: 190.0, bb_middle: 178.5, bb_lower: 167.0 },
    { date: "2025-01-14", sma_20: 179.0, sma_50: 172.5, sma_200: 165.2, ema_20: 180.0, ema_50: 173.5, bb_upper: 191.0, bb_middle: 179.0, bb_lower: 167.0 },
    { date: "2025-01-15", sma_20: 179.5, sma_50: 172.8, sma_200: 165.3, ema_20: 180.5, ema_50: 174.0, bb_upper: 191.5, bb_middle: 179.5, bb_lower: 167.5 },
  ],
};

export const mockRankingsResponse: RankingsResponse = {
  generated_at: "2025-01-15T10:00:00Z",
  total_symbols: 100,
  split_suspect_symbols: 2,
  longs: [
    {
      rank: 1,
      symbol: "AAPL",
      company_name: "Apple Inc.",
      sector: "Technology",
      composite_score: 82.5,
      action: "Strong Buy",
      decision_action: "STRONG_BUY",
      decision_confidence: "HIGH",
      decision_score: 82.5,
      guardrails_triggered: [],
      decision_policy: null,
      target_return_pct: 15.3,
      valuation_basis: "DCF",
    },
    {
      rank: 2,
      symbol: "MSFT",
      company_name: "Microsoft Corp.",
      sector: "Technology",
      composite_score: 78.0,
      action: "Buy",
      decision_action: "BUY",
      decision_confidence: "MEDIUM",
      decision_score: 78.0,
      guardrails_triggered: [],
      decision_policy: null,
      target_return_pct: 12.1,
      valuation_basis: "P/E Relative",
    },
    {
      rank: 3,
      symbol: "GOOGL",
      company_name: "Alphabet Inc.",
      sector: "Technology",
      composite_score: 75.0,
      action: "Buy",
      decision_action: "BUY",
      decision_confidence: "MEDIUM",
      decision_score: 75.0,
      guardrails_triggered: [],
      decision_policy: null,
      target_return_pct: 10.5,
      valuation_basis: "DCF",
    },
  ],
  shorts: [
    {
      rank: 1,
      symbol: "XYZ",
      company_name: "XYZ Corp.",
      sector: "Consumer Discretionary",
      composite_score: 25.0,
      action: "Sell",
      decision_action: "SELL",
      decision_confidence: "MEDIUM",
      decision_score: 25.0,
      guardrails_triggered: [],
      decision_policy: null,
      target_return_pct: -12.0,
      valuation_basis: "P/E Relative",
    },
  ],
  sector_neutral: [
    {
      sector: "Technology",
      longs: [
        {
          rank: 1,
          symbol: "AAPL",
          company_name: "Apple Inc.",
          sector: "Technology",
          composite_score: 82.5,
          action: "Strong Buy",
          decision_action: "STRONG_BUY",
          decision_confidence: "HIGH",
          decision_score: 82.5,
          guardrails_triggered: [],
          decision_policy: null,
          target_return_pct: 15.3,
          valuation_basis: "DCF",
        },
      ],
      shorts: [
        {
          rank: 1,
          symbol: "INTC",
          company_name: "Intel Corp.",
          sector: "Technology",
          composite_score: 30.0,
          action: "Sell",
          decision_action: "SELL",
          decision_confidence: "MEDIUM",
          decision_score: 30.0,
          guardrails_triggered: [],
          decision_policy: null,
          target_return_pct: -8.0,
          valuation_basis: "DCF",
        },
      ],
    },
  ],
  pairs: [
    {
      long: {
        rank: 1,
        symbol: "AAPL",
        company_name: "Apple Inc.",
        sector: "Technology",
        composite_score: 82.5,
        action: "Strong Buy",
        decision_action: "STRONG_BUY",
        decision_confidence: "HIGH",
        decision_score: 82.5,
        guardrails_triggered: [],
        decision_policy: null,
        target_return_pct: 15.3,
        valuation_basis: "DCF",
      },
      short: {
        rank: 1,
        symbol: "INTC",
        company_name: "Intel Corp.",
        sector: "Technology",
        composite_score: 30.0,
        action: "Sell",
        decision_action: "SELL",
        decision_confidence: "MEDIUM",
        decision_score: 30.0,
        guardrails_triggered: [],
        decision_policy: null,
        target_return_pct: -8.0,
        valuation_basis: "DCF",
      },
      sector: "Technology",
      spread: 52.5,
    },
  ],
};

export const mockSymbolSearchResults: SymbolSearchResult[] = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology", industry: "Consumer Electronics" },
  { symbol: "AAPLX", name: "Apple Fund", sector: "Finance", industry: "Mutual Funds" },
];

export const mockPredictionsResponse: PredictionsResponse = {
  symbol: "AAPL",
  predictions: [
    {
      id: 1,
      symbol: "AAPL",
      analysis_date: "2025-01-15",
      blended_fair_value: 195.0,
      current_price: 182.5,
      predicted_upside_pct: 6.85,
      model_fair_values: { dcf: 200.0, pe: 188.0, ps: null, ev_ebitda: 192.0, pb: null, ggm: 201.0 },
      actual_price_30d: 190.0,
      actual_price_90d: 198.0,
      actual_price_365d: null,
      reward_30d: 0.8,
      reward_90d: 0.9,
      tier_classification: "high_conviction",
    },
    {
      id: 2,
      symbol: "AAPL",
      analysis_date: "2024-12-01",
      blended_fair_value: 180.0,
      current_price: 175.0,
      predicted_upside_pct: 2.86,
      model_fair_values: { dcf: 185.0, pe: 178.0, ps: null, ev_ebitda: 177.0, pb: null, ggm: 180.0 },
      actual_price_30d: 170.0,
      actual_price_90d: null,
      actual_price_365d: null,
      reward_30d: -0.3,
      reward_90d: null,
      tier_classification: "moderate",
    },
  ],
};
